apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: raisa-testpy 
  janus-idp.io/tekton: raisa-testpy
  backstage.io/kubernetes-id: raisa-testpy
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: raisa-testpy
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  